:PROPERTIES:
:ID:       f9463952-6478-4ea8-91d6-4f856720a8d4
:END:
#+title: Cultural dependency of Causal Models

Throughout history, our understanding of the world has undergone radical changes even though we have inhabited the same universe. See [[https://en.wikipedia.org/wiki/Superseded_theories_in_science_and_results_in_mathematics][this Wikipedia page]] for examples. Not only do the relations between the entities change, but even the existence of entities themselves. 

I'm agnostic to the question of whether or not nature operates according to a unique [[id:4fbaec1f-4d09-4c1a-9621-ceeab7a00837][causal model]]. Such a causal model is unobservable, unless perhaps one is a God themselves. However, I take up the position that, even though we may come up with /a/ causal model for a given phenomena, it'd be mistaken to consider it as /the/ causal model. In other words, totally objective criteria for evaluating causal models of a phenomena do not exist. If it were possible to come up with completely objective causal models and methods for evaluating them, scientific theories would never have evolved or replaced.

However, scientific theories of natural as well as manmade phenomena, as well as our layman understanding of how the society works are reasonably stable in a given spacetime locality. Thus, even though, we cannot come up with true causal models of the world, in a given spacetime locality, we all share reasonably common causal understanding with each other. This is the /cultural dependency of causal models/.

I propose that this has implications for [[id:20428c0a-b49d-4569-83f4-14ad771a798a][how we formalize causality]]. 

TODO: 

1. The exact mechanisms for how children acquire causal variables and models from their culture.
2. Replicating those mechanisms in machines. 
