:PROPERTIES:
:ID:       723fc245-dffe-40d6-915c-59c529816011
:END:
#+title: Causality as Counterfactuals

The notion of causality may be summarized by "given that B caused / was prevented after A, had A not occurred, then B would be less/more likely to have occurred". In this case, A becomes a cause of B. This allows us to /counterfactually reason/ in order to bring about or prevent B by manipulating A.

I had earlier [[id:3786c406-d58c-480b-afea-b876583e8e67][equated causality with interventions]], but causality - as proposed by Pearl and agreed by others - goes beyond interventions and incorporates counterfactual reasoning. 

Future Work:

- What exactly are Counterfactuals? (Reference: https://en.wikipedia.org/wiki/Counterfactual_conditional)
- Why do I seem to have a hard time processing counterfactuals?
- How do counterfactuals differ from interventions?
- Has easy internet access diminished our conterfactual thinking abilities?
- Are counterfactuals really the core of causal reasoning? See [[https://ojs.aaai.org/index.php/HCOMP/article/view/22001][this]] for instance.
